main: me.herobrinedobem.heventos.HEventos
name: HEventosReloaded
version: 1.6.3
author: GabrielDev
description: Plugin de eventos automaticos

commands:
    evento:
        description: Todos os comandos do plugin